//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransactionService.Customer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public long id { get; set; }
        public long customer_id { get; set; }
        public string customer_name { get; set; }
        public string contact_email { get; set; }
        public long mobile_no { get; set; }
        public long transaction_id { get; set; }
    }
}
