//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransactionService.Customer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public long transaction_id { get; set; }
        public string transaction_date { get; set; }
        public decimal amount { get; set; }
        public string currency_code { get; set; }
        public string status { get; set; }
        public long customer_id { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
